version: '3'

services:
  mysql:
    image: mysql:5.5
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  php:
    build: docker/php
    volumes:
      - ./:/var/www
    env_file:
      - .env
    ports:
      - "${APACHE_PORT}:80"